In [15]:
import numpy as np

arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)

matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
import numpy as np

arr = np.random.rand(10)

print("Array:", arr) 
print("Mean:", arr.mean())
print("Median:", np.median(arr))
print("Standard Deviation:", arr.std())

Array: [0.00420941 0.80003948 0.63158725 0.70176255 0.06726348 0.41889689
 0.0235718  0.78917754 0.74764258 0.51232823]
Mean: 0.46964792042071135
Median: 0.5719577419726849
Standard Deviation: 0.30831279114590526


In [28]:
import numpy as np

data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
data[data % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [29]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
addition = A + B
print("Matrix Addition:\n", addition)

multiplication = A * B
print("Matrix Multiplication:\n", multiplication )


Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
