In [1]:
import numpy as np

arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)
matrix 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [2]:
import numpy as np

arr = np.random.rand(10)

print("Array:", arr)
print("Mean:", arr.mean())
print("Median:", np.median(arr))
print("Standard Deviation:", arr.std())

Array: [0.92037323 0.2041625  0.19776502 0.7475033  0.29010014 0.77919326
 0.51823843 0.63898648 0.17686596 0.37951021]
Mean: 0.48526985354807584
Median: 0.4488743198602344
Standard Deviation: 0.2598572061428053


In [4]:
import numpy as np

data = np.array([12, 56, 98, 76, 34, 11, 13, 17, 20,90])
data[data % 2 != 0]

array([11, 13, 17])

In [11]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
addition = A + B
print("Matrix Addition:\n", addition)

multiplication = A * B
print("Matrix Multiplication:\n", multiplication )


Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
